main:
	g++ -std=c++11 -O3 -I/usr/include/mysql -o ../get-edges.bin get-edges.cpp -L/usr/lib/x86_64-linux-gnu -lmysqlclient
	g++ -std=c++11 -O3 -I/usr/include/mysql -o ../get-nodes.bin get-nodes.cpp -L/usr/lib/x86_64-linux-gnu -lmysqlclient

